Document: sandbox
Title: Debian sandbox Manual
Author: <insert document author here>
Abstract: This manual describes what sandbox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sandbox/sandbox.sgml.gz

Format: postscript
Files: /usr/share/doc/sandbox/sandbox.ps.gz

Format: text
Files: /usr/share/doc/sandbox/sandbox.text.gz

Format: HTML
Index: /usr/share/doc/sandbox/html/index.html
Files: /usr/share/doc/sandbox/html/*.html
